AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'

Naming/MethodParameterName:
  MinNameLength: 1

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 75

Metrics/ClassLength:
  Max: 250

Metrics/MethodLength:
  Max: 25
