name: Math RSpec

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.6, 2.7, 3.0]
    name: Ruby ${{ matrix.ruby }} RSpec
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rake spec
  build:
    runs-on: ubuntu-latest
    name: Rubocop
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rubocop
